### ISSUE TITLE
Mid-game upgrade script

### ISSUE THREAD

**Issue by Pickysaurus** [Starfield-Community-Patch/Starfield-Community-Patch#553]
We should look at adding a migration handler to the patch which will apply fixes retro-actively without requiring the player to enter NG+ to take advantage of the changes. 

A running list of known script we will need to migrate is shown below:

- [ ] Constellation companions no longer have the wrong dialogue in NG+ after completing "Foreknowledge". [qf_mq204_002c6d74] #164
- [ ] The number of undiscovered temples shown in the UI will now match how many are actually undiscovered. [starborntemplequestscript] #231 
- [ ] The doors to Coe Estate will now properly unlock on entering NG+ [qf_mq401_001dc45e] #370 
- [ ] The variable indicating that you had previously met Lillian during Sam Coe's questline will now be properly set. [qf_mq401_001dc45e] #373 (Possibly not fixable as in NG+ the only way to know if the player has met Lillian is to check this value!)
- [ ] The variable indicating that you had previously completed Sam Coe's commitment questline will now be properly set. [qf_com_quest_samcoe_commitme_000df7ad] #369  (Possibly not fixable as in NG+ the only way to know if the player has met Lillian is to check this value!)
- [ ] Cora Coe will now correctly join the player's crew when Sam is recruited as a companion or crew member in NG+ [qf_mq401_001dc45e] #369
- [ ] Fixed a potential softlock issue when arriving in a variant universe in NG+ [mq401questscript] #314
